language: cpp

os: linux

dist: focal

cache:
  directories:
    - ${HOME}/PawPawBuilds/builds
    - ${HOME}/PawPawBuilds/debs
    - ${HOME}/PawPawBuilds/downloads
    - ${HOME}/PawPawBuilds/targets/macos
    - ${HOME}/PawPawBuilds/targets/macos-universal
    - ${HOME}/PawPawBuilds/targets/win32
    - ${HOME}/PawPawBuilds/targets/win64

env:
  global:
    - BOOTSTRAP_VERSION=2

jobs:
  # linux with win32 cross-compilation
  - name: "win32 cross-compiled"
    os: linux
    compiler: gcc
    env:
      - TARGET="win32"
    services:
      - xvfb

  # linux with win64 cross-compilation
  - name: "win64 cross-compiled"
    os: linux
    compiler: gcc
    env:
      - TARGET="win64"
    services:
      - xvfb

  # macOS native intel build
  - name: "macOS native intel"
    os: osx
    osx_image: xcode9.4
    env:
      - TARGET="macos"

  # macOS universal build
  - name: "macOS universal"
    os: osx
    osx_image: xcode12.3
    env:
      - TARGET="macos-universal"

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
  - bash ${TRAVIS_BUILD_DIR}/build.sh ${TARGET}

deploy:
  provider: releases
  api_key:
    secure: "afKJTgVeXjuOSTqnkvYBK129dwgIhfEuw98DmCDmEeW/+IeUBZC1PtnvlDAxxsqExZgdCi1i+8fRzdFGQS6GpNx6IZzIZs/DETR0XjNdtf6gZLwnCC98OskqG724P0qlW+DJFU4cfje7iYw75UbDEFlTosgFqIeNC0oBi1APTIQM3AtfyK5HqGCqRORzQBuBoE7JaJDTiY31W1hiXhJrUZZVP9ne5Gxl81SeOEUUrofaP91z4BBifr9ffZyFONdJTjBv3UnKyajDoORZkgE97hknLVaXMkOTKRmA4BIFbu0ag0/TW/8JGyEca/uQFX14LS1qWRNoLVajaWiZrHlo4qwznQE4S2jGWu1vMitbqqlkNG2ps75Qs45KoKluBo5hwoe6LNUn8aIacji+pEe+JTGOHArWgnPP5qJpDQgDy2HhINxEU0aFm89vJWaavWwQmDEDpwrcpa81mOG5XCMlpAVBcqfXU35j/mxT/nn7eLnCAnxXgayS81AovlbBJTZf9F8XVoK+XlMUwuL5Dk56SfnSGIXEGLgrdxSwkKMr3lRiDzIB9lzv7U/QXlvX/6n3YwW9GucsVa5C1I79t4FOFIX1xNUzj7No2EwnTSiQfte8GmfGw0SuqRM6SKd6JnQvISZ5zx+/NEKODMPWrFPRy9uluChr9t5KUOmC9HNFdUU="
  file_glob: true
  file:
    - Carla/*.dmg
    - Carla/*.zip
  skip_cleanup: true
  on:
    tags: true
